### ISSUE TITLE
[BUG] 게시글 제목이 없을 때, 에러 발생

### ISSUE THREAD

**Issue by MunSeongyun** [WhileNotSuccess/practice_community_react#59]
**버그 설명**
게시글 작성시 제목을 안 쓰거나 내용을 안 쓰면 alert를 사용해서 알림을 띄우거나 해야하는데, 그런게 없음. 백엔드에서는 제목이나 내용이 없으면, 받아드리지 않는데, 프론트는 반응이 없음. .catch 구문을 사용해서 에러메시지를 alert로 띄우면 될듯

**버그 재현 과정**
다른 사람도 확인할 수 있도록 버그를 일으키는 방법을 알려주세요
1. /post로 이동
2. 글 내용만 작성하거나, 제목만 작성
3. 네트워크 확인
4. 에러 확인

**기대했던 동작**
제목이나 내용을 작성하라는 경고창이 뜨길 기대함

**추가**
항상 .then 뒤에는 .catch로 경고창을 띄우는걸 습관화 해주세요

**Comment by kwongihyeon** [comment]
.catch에 조건을 주고 제목을 적지 않은경우는 제목을 입력하세요 라는문구를 내용을 적지 않은 경우는 내용을 입력하세요라는 문구를 띄우게 수정하였습니다
